<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.mytime.testsuite.NewTest" tests="2" time="75.782" ignored="0" failures="2" timestamp="26 Sep 2018 09:26:17 GMT" skipped="0" hostname="DESKTOP-OAN6F8S" errors="0">
  <testcase name="tearDown" time="2.966" classname="com.mytime.testsuite.NewTest">
    <failure type="java.lang.AssertionError" message="Given web element: By.className: dropdown-toggle was not found on the web page">
      <![CDATA[java.lang.AssertionError: Given web element: By.className: dropdown-toggle was not found on the web page
	at org.testng.Assert.fail(Assert.java:94)
	at com.nisum.qa.automation.components.Clicks.userClick(Clicks.java:53)
	at com.mytime.pages.LoginPage.logout(LoginPage.java:55)
	at com.mytime.testsuite.NewTest.tearDown(NewTest.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:712)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- tearDown -->
  <testcase name="updateAccount" time="72.816" classname="com.mytime.testsuite.NewTest">
    <failure type="java.lang.AssertionError" message="By.xpath: //*[contains(@class , &#039;ng-binding&#039;)and text()=&#039;Account assigned successfully&#039;] was not displayed in time - 10 Seconds - TimeoutException">
      <![CDATA[java.lang.AssertionError: By.xpath: //*[contains(@class , 'ng-binding')and text()='Account assigned successfully'] was not displayed in time - 10 Seconds - TimeoutException
	at org.testng.Assert.fail(Assert.java:94)
	at com.nisum.qa.automation.components.TimeOutMethods.whetherElementClickable(TimeOutMethods.java:139)
	at com.nisum.qa.automation.components.TextField.userGetTextFromWebElement(TextField.java:56)
	at com.mytime.pages.ManageAccountPage.verifySuccessMessage(ManageAccountPage.java:42)
	at com.mytime.pages.ManageAccountPage.updateAccount(ManageAccountPage.java:79)
	at com.mytime.testsuite.NewTest.addOrUpdateAccount(NewTest.java:98)
	at com.mytime.testsuite.NewTest.addOrUpdate(NewTest.java:151)
	at com.mytime.testsuite.NewTest.updateAccount(NewTest.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- updateAccount -->
</testsuite> <!-- com.mytime.testsuite.NewTest -->
